rss_parsing_task:
  description: >
    Parse each RSS feed, retain all the news articles.
    Filter all the EV-related news.
    rss_urls = [
    "https://rss.app/feeds/u6rcvfy6PTSf9vQ4.xml",
    "https://www.carblog.co.uk/feed/",
    "https://arrowcarhire.co.uk/feed/",
    "https://thedriversden.com/articles?format=rss",
    "https://www.carthrottle.com/rss",
    "https://www.fundmycarscotland.com/feed/",
    "https://carleasespecialoffers.co.uk/blog/feed/",
    "https://regcarcheck.co.uk/feed/",
    "https://carwitter.com/feed/",
    "https://www.autocar.co.uk/rss",
    "https://ottocar.co.uk/pco-blog/feed/",
    "http://www.theultimatefinish.co.uk/car-care-blog/feed/",
    "https://www.ecurie.co.uk/blog?format=rss",
    "https://www.carbuyer.co.uk/rss/news",
    "https://www.thedrive.co.uk/feed/",
    "https://www.whiterecovery.co.uk/feed/",
    "https://www.driving-news.co.uk/feed/",
    "https://www.splend.co.uk/blog/feed/",
    "https://cardealermagazine.co.uk/publish/category/latest-news/feed",
    "https://smart-motoring.com/feed/",
    "https://webloganycar.co.uk/feed/",
    "https://www.hiyacar.co.uk/blog/feed.xml",
    "https://www.actonservicecentre.co.uk/feed/",
    "https://petrolblog.com/feed",
    "https://www.fastcar.co.uk/feed/",
    "https://www.taketotheroad.co.uk/feed/",
    "https://www.motorverso.com/feed/",
    "https://classicmotorhub.com/category/blog/feed/",
    "https://carfinancegenie.co.uk/feed/",
    "https://www.eurocarparts.com/blog/feed",
    "https://rearviewprints.com/feed/",
    "https://dailycarblog.com/feed/",
    "http://automotiveblog.co.uk/feed/",
    "https://thecarscene.co.uk/feed",
    "https://co-cars.co.uk/feed/",
    "https://www.jct600.co.uk/blog/feed/",
    "https://www.thecarexpert.co.uk/feed/",
    "https://automotiveblog.co.uk/feed/",
    "https://www.hiltoncarsupermarket.co.uk/rss.php",
    "https://www.autoexpress.co.uk/feeds/all",
    "https://planetauto.co.uk/index.php?format=feed&type=rss"
    ]
  expected_output: >
    A structured JSON file containing all the EV-related articles with their title, 
    publication date, source.
  agent: rss_reader_scraper
  output_file: ev_news_parsed.json

information_gathering_task:
  description: >
    Enrich the filtered EV-related news articles by gathering supplementary 
    information from multiple credible sources to add context and depth.
  expected_output: >
    A JSON file containing the original articles enriched with additional information 
    and a list of sources.
  agent: information_aggregator
  output_file: ev_news_enriched.json

quality_evaluation_task:
  description: >
    Evaluate the enriched EV news articles for reliability, relevance, and quality. 
    Assign a quality score and rank the articles based on these criteria.
  expected_output: >
    A JSON file containing the ranked articles with their quality scores.
  agent: quality_evaluator
  output_file: ev_news_ranked.json

news_writing_task:
  description: >
    Write polished and engaging EV news articles based on the ranked and evaluated data. 
    Ensure the content is professional, reader-friendly, and formatted for publication.
  expected_output: >
    A JSON file with the final news articles, it should contain labels:
    title, description, content, link, published_at

    content should be a professional EV news article based on curated and evaluated information
    link contain all its sources link.

  agent: news_writer
  output_file: ev_news_final.json

